create index workspace_members_user_idx on public.workspace_members(user_id, status);
create index activity_events_workspace_created_idx on public.activity_events(workspace_id, created_at desc);
create index company_profile_versions_profile_idx on public.company_profile_versions(company_profile_id, version desc);
create index campaigns_workspace_status_idx on public.campaigns(workspace_id, status);
create index campaign_strategy_versions_campaign_idx on public.campaign_strategy_versions(campaign_id, version desc);
create index campaign_runs_campaign_created_idx on public.campaign_runs(campaign_id, created_at desc);
create index campaign_runs_workspace_status_idx on public.campaign_runs(workspace_id, status, created_at desc);
create index campaign_run_events_run_created_idx on public.campaign_run_events(campaign_run_id, created_at);
create index campaign_questions_open_idx on public.campaign_questions(campaign_run_id, status) where status = 'open';
create index campaign_approvals_pending_idx on public.campaign_approvals(campaign_run_id, status) where status = 'pending';
create index companies_workspace_name_idx on public.companies(workspace_id, normalized_name);
create index company_domains_company_idx on public.company_domains(company_id);
create index company_sources_company_idx on public.company_sources(company_id, retrieved_at desc);
create index campaign_companies_campaign_status_idx on public.campaign_companies(campaign_id, status);
create index campaign_companies_company_idx on public.campaign_companies(company_id);
create index qualification_results_campaign_company_idx on public.qualification_results(campaign_company_id, created_at desc);
create index qualification_evidence_result_idx on public.qualification_evidence(qualification_result_id);
create index contacts_company_idx on public.contacts(company_id);
create index contact_methods_company_idx on public.contact_methods(company_id, method_type);
create index campaign_contacts_company_idx on public.campaign_contacts(campaign_company_id, selection_status);
create index outreach_drafts_campaign_idx on public.outreach_drafts(campaign_id, status, created_at desc);
create index export_records_campaign_idx on public.export_records(campaign_id, created_at desc);
create index documents_workspace_status_idx on public.documents(workspace_id, status);
create index document_chunks_document_idx on public.document_chunks(document_id, chunk_index);
create index campaign_memories_campaign_idx on public.campaign_memories(campaign_id, category);
create index workspace_memories_workspace_idx on public.workspace_memories(workspace_id, category);
create index provider_executions_run_idx on public.provider_executions(campaign_run_id, created_at desc);
create index ai_requests_run_idx on public.ai_requests(campaign_run_id, created_at desc);
create index usage_ledger_workspace_created_idx on public.usage_ledger(workspace_id, created_at desc);
create index budget_reservations_run_status_idx on public.budget_reservations(campaign_run_id, status);
create index ai_messages_conversation_idx on public.ai_messages(conversation_id, created_at);

