import assert from "node:assert/strict";
import test from "node:test";
import { runBoundedCompanyAnalyst } from "./bounded-analyst.ts";
import { assertAnalystEvidenceBoundary, companyAnalystResultSchema } from "./company-analyst.ts";

function result(status:"complete"|"needs_research"="complete") {
  return companyAnalystResultSchema.parse({status,overview:"A commercially coherent company.",companyFacts:[{key:"industry",value:"Hospitality supply",epistemicStatus:"explicit_fact",confidence:.9,evidenceIds:["e1"]}],offerings:[{key:"equipment",name:"Equipment",shortDescription:"Professional equipment",commercialUse:"Operational use",buyingMotion:"project",customerConsumptionMode:"use",customerProblems:[],expectedOutcomes:[],confidence:.9,evidenceIds:["e1"]}],targetOrganisations:[{key:"hotels",name:"Hotels",shortDescription:"Hotel operators",relevantOfferingKeys:["equipment"],relationshipType:"buyer",whyCompatible:[],likelyNeeds:[],scaleDrivers:[],buyingTriggers:[],likelyDecisionRoles:["Procurement Manager"],confidence:.7,epistemicStatus:"evidence_backed_inference",evidenceIds:["e1"]}],targetRoles:[{key:"procurement",label:"Procurement Manager",relevantOfferingKeys:["equipment"],relevantTargetOrganisationKeys:["hotels"],confidence:.7,evidenceIds:["e1"]}],knownRelationships:[],constraints:[],uncertainties:[],researchRequests:status==="needs_research"?[{key:"service",question:"Confirm whether installation is a distinct commercial service.",reason:"This changes whether installation is represented as an offering.",suggestedSearchTerms:["installation service"],preferredSourceType:"seller_site",priority:"high"}]:[]});
}

test("sufficient evidence uses exactly one analyst round and no research", async()=>{let calls=0,research=0;const run=await runBoundedCompanyAnalyst({analyze:async()=>{calls++;return result();},research:async()=>{research++;return [];},validate:()=>{}});assert.equal(calls,1);assert.equal(research,0);assert.equal(run.rounds,1);});
test("material gaps use bounded research and exactly one final analyst round",async()=>{let calls=0,research=0;const run=await runBoundedCompanyAnalyst({analyze:async round=>{calls++;return result(round===1?"needs_research":"complete");},research:async requests=>{research++;assert.equal(requests.length,1);return ["new evidence"];},validate:()=>{}});assert.equal(calls,2);assert.equal(research,1);assert.equal(run.rounds,2);});
test("a second research request never creates a third analyst round",async()=>{let calls=0;const run=await runBoundedCompanyAnalyst({analyze:async()=>{calls++;return result("needs_research");},research:async()=>[],validate:()=>{}});assert.equal(calls,2);assert.equal(run.result.status,"complete");assert.equal(run.result.researchRequests.length,0);assert.match(run.result.uncertainties[0]!,/installation/i);});
test("analyst evidence is restricted to evidence visible in its round",()=>{const invalid={...result(),offerings:[{...result().offerings[0]!,evidenceIds:["invented"]}]};assert.throws(()=>assertAnalystEvidenceBoundary(invalid,new Set(["e1"])),/not visible/);});
test("ambiguous logo mentions cannot become confirmed customers",()=>{const invalid={...result(),knownRelationships:[{organisationName:"Logo Co",canonicalDomain:null,relationshipType:"existing_customer" as const,status:"confirmed" as const,source:"seller_site" as const,confidence:.95,evidenceIds:["e1"]}]};assert.throws(()=>assertAnalystEvidenceBoundary(invalid,new Set(["e1"]),new Map([["e1","Logo Co"]])),/high-confidence explicit evidence/);});
