import type { CompanyAnalystResult } from "./company-analyst.ts";
import { profileBuyerLogicOutputSchema, profileClarificationOutputSchema, profileCommercialSynthesisOutputSchema, profileOfferingDecompositionOutputSchema } from "./task-contracts.ts";

export function adaptCompanyAnalystResult(result: CompanyAnalystResult) {
  const consumptionModes=[...new Set(result.offerings.map(({customerConsumptionMode})=>customerConsumptionMode==="mixed"?"unknown":customerConsumptionMode))];
  const commercial = profileCommercialSynthesisOutputSchema.parse({primaryRoles:[],valueChainPosition:[],revenueMechanics:result.commercialMechanics.revenueModels.map(mechanism=>({mechanism,status:"evidence_backed_inference",confidence:.7,evidenceIds:[]})),transactionModels:result.commercialMechanics.transactionModels,deliveryModels:result.commercialMechanics.deliveryModels,customerConsumptionModes:consumptionModes.length?consumptionModes:["unknown"],channelModels:[],commercialConstraints:[],unresolvedCommercialQuestions:result.uncertainties,conciseCommercialSummary:result.overview,knownRelationships:result.knownRelationships.map(({organisationName,source,...relationship})=>({...relationship,organizationName:organisationName,source:source==="seller_site"?"seller_site":source==="user_confirmed"||source==="profile_memory"?"company_profile":"other"}))});
  const offerings = profileOfferingDecompositionOutputSchema.parse({offerings:result.offerings.map(o=>({offeringKey:o.key,name:o.name,offeringType:"commercial_offering",shortDescription:o.shortDescription,includedItemKeys:[],excludedItemKeys:[],valueProposition:o.commercialUse,customerProblems:o.customerProblems,expectedOutcomes:o.expectedOutcomes,customerConsumptionMode:o.customerConsumptionMode,buyingMotion:o.buyingMotion,dependencies:[],commercialConstraints:result.constraints,evidenceIds:o.evidenceIds,confidence:o.confidence})),ungroupedItems:[],groupingWarnings:[]});
  const archetypes=result.targetOrganisations.flatMap(target=>target.relevantOfferingKeys.map((offeringKey,index)=>({archetypeKey:index?`${target.key}-${offeringKey}`:target.key,offeringKey,name:target.name,relationshipType:target.relationshipType,priority:"priority" as const,description:target.shortDescription,businessRoles:[],businessModels:[],industries:[],whyCompatible:target.whyCompatible,requiredConditions:target.likelyNeeds,preferredConditions:[],incompatibleConditions:[],requiredEvidence:[],positiveSignals:target.scaleDrivers,negativeSignals:[],scaleSignals:target.scaleDrivers,buyingTriggers:target.buyingTriggers,likelyDecisionRoles:target.likelyDecisionRoles,evidenceIds:target.evidenceIds,epistemicStatus:target.epistemicStatus,confidence:target.confidence}))).slice(0,24);
  const buyerLogic=profileBuyerLogicOutputSchema.parse({offeringBuyerLogic:result.offerings.map(o=>{const targets=result.targetOrganisations.filter(t=>t.relevantOfferingKeys.includes(o.key));return {offeringKey:o.key,whyBuy:o.expectedOutcomes.length?o.expectedOutcomes:[o.commercialUse||o.shortDescription],requiredConditions:[...new Set(targets.flatMap(t=>t.likelyNeeds))].slice(0,4),preferredConditions:[],likelyTriggers:[...new Set(targets.flatMap(t=>t.buyingTriggers))].slice(0,4),incompatibleConditions:[],likelyDecisionRoles:[...new Set(targets.flatMap(t=>t.likelyDecisionRoles))].slice(0,6),positiveEvidenceSignals:[...new Set(targets.flatMap(t=>t.scaleDrivers))].slice(0,5),negativeEvidenceSignals:[],evidenceIds:o.evidenceIds,confidence:o.confidence};}),archetypes,proposedOfferingRules:[],unresolvedQuestions:result.uncertainties});
  const clarification=profileClarificationOutputSchema.parse({questions:[],omittedQuestions:result.uncertainties.map(topic=>({topic,omissionReason:"Profile remains usable; uncertainty is preserved for review."}))});
  return {commercial,offerings,buyerLogic,clarification};
}
