import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { adaptCompanyAnalystResult } from "./company-analyst-adapter.ts";
import { assertAnalystEvidenceBoundary, classifyFollowUpProvenance, companyAnalystCacheKey, companyAnalystResultSchema, remapCachedAnalystEvidence } from "./company-analyst.ts";
import { finalizeCompiledSnapshot } from "./draft-compiler.ts";

function result(){return companyAnalystResultSchema.parse({status:"complete",overview:"Makes pharmaceutical products.",companyFacts:[],offerings:[{key:"api",name:"API",shortDescription:"Active ingredients",commercialUse:"Integrated into medicines",buyingMotion:"wholesale_order",customerConsumptionMode:"integrate",customerProblems:[],expectedOutcomes:[],confidence:.9,evidenceIds:["old-1"]},{key:"licensing",name:"Licensing",shortDescription:"Medicine licences",commercialUse:"Portfolio expansion",buyingMotion:"license",customerConsumptionMode:"license",customerProblems:[],expectedOutcomes:[],confidence:.8,evidenceIds:["old-1"]}],targetOrganisations:[{key:"pharma",name:"Pharma companies",shortDescription:"Medicine manufacturers",relevantOfferingKeys:["api","licensing"],relationshipType:"buyer",confidence:.8,epistemicStatus:"hypothesis",evidenceIds:["old-1"]}],targetRoles:[{key:"bd",label:"Business Development Director",relevantOfferingKeys:["licensing"],relevantTargetOrganisationKeys:["pharma"],confidence:.8,evidenceIds:["old-1"]}],knownRelationships:[],constraints:[],uncertainties:[],researchRequests:[]});}

test("follow-up provenance distinguishes seller and external domains",()=>{assert.deepEqual(classifyFollowUpProvenance("https://shop.example.com/services",["example.com"]),{directness:"direct",sourceReliability:"first_party",relationshipSource:"seller_site"});assert.deepEqual(classifyFollowUpProvenance("https://trade.example.net/story",["example.com"]),{directness:"indirect",sourceReliability:"unverified_secondary",relationshipSource:"third_party"});});
test("confirmed relationship evidence must match its exact type",()=>{const customer={...result(),knownRelationships:[{organisationName:"ABC",canonicalDomain:null,relationshipType:"existing_customer" as const,status:"confirmed" as const,source:"seller_site" as const,confidence:.95,evidenceIds:["old-1"]}]};assert.throws(()=>assertAnalystEvidenceBoundary(customer,new Set(["old-1"]),new Map([["old-1","ABC is our distribution partner"]])),/explicit evidence/);const distributor={...customer,knownRelationships:[{...customer.knownRelationships[0]!,relationshipType:"distributor" as const}]};assert.doesNotThrow(()=>assertAnalystEvidenceBoundary(distributor,new Set(["old-1"]),new Map([["old-1","ABC is an authorised distributor"]])));});
test("cache remapping is all-or-nothing and includes target roles",()=>{const cached=result();const hit=remapCachedAnalystEvidence(cached,{"old-1":"hash-1"},new Map([["hash-1","new-1"]]));assert.ok(hit);assert.deepEqual(hit.targetRoles[0]?.evidenceIds,["new-1"]);assert.equal(remapCachedAnalystEvidence(cached,{"old-1":"hash-1"},new Map()),null);const bad={...cached,targetRoles:[{...cached.targetRoles[0]!,evidenceIds:["unknown"]}]};assert.throws(()=>assertAnalystEvidenceBoundary(bad,new Set(["old-1"])),/not visible/);});
test("confirmed inputs invalidate the analyst cache key",()=>{const base={companyProfileId:"p",evidenceHashes:["h"],promptVersion:"p1",schemaVersion:"s1",contextCompilerVersion:"c1",analystVersion:"a1"};assert.notEqual(companyAnalystCacheKey({...base,confirmedUserInput:{directSales:false}}),companyAnalystCacheKey({...base,confirmedUserInput:{directSales:true}}));});
test("compatibility adapter preserves consumption modes and relationship source",()=>{const input={...result(),knownRelationships:[{organisationName:"Registry Co",canonicalDomain:null,relationshipType:"partner" as const,status:"probable" as const,source:"third_party" as const,confidence:.7,evidenceIds:["old-1"]}]};const adapted=adaptCompanyAnalystResult(input);assert.deepEqual(adapted.offerings.offerings.map(item=>item.customerConsumptionMode),["integrate","license"]);assert.equal(adapted.commercial.knownRelationships[0]?.source,"other");});
test("compiled snapshot hashes include the analyst result",()=>{const one=finalizeCompiledSnapshot({identity:"same"},result());const two=finalizeCompiledSnapshot({identity:"same"},{...result(),overview:"Different analyst result."});const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");assert.notEqual(hash(one),hash(two));});
